apiVersion: v1
kind: Service
metadata:
  labels:
    app: key-generator-service
  name: key-generator
spec:
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  selector:
    app: key-generator-service
