apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiny-url-ingress
spec:
  rules:
    - host: mytinyurl.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tiny-url-api
                port:
                  number: 9093
