apiVersion: v1
kind: Service
metadata:
  labels:
    app: tiny-url-mongodb-service
  name: tiny-url-mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: tiny-url-mongodb-service
