apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tiny-url-mongodb-service
  name: tiny-url-mongodb-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-url-mongodb-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tiny-url-mongodb-service
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo
          name: tiny-url-mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-init-db
            - mountPath: /data/db
              name: mongodb-data
      restartPolicy: Always
      volumes:
        - name: mongo-init-db
          configMap:
            name: tiny-url-mongodb-config
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
