apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tiny-url-mongodb-service
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
