github-client-id: '9d8c01dd4e8fa7fd0603'
github-client-secret: '924746310d082820e835fed48e6fcfe19edb2c85'

node-id: 1001
key-generation-strategy: 'TwitterSnowflakeKeyGenerator'
key-replenish-threshold: 2

redis-host-url: localhost
redis-port: 6379
