server:
  shutdown: graceful
  port: ${SERVER-PORT:8093}

key-generator:
  name: 'TwitterSnowflakeKeyGenerator'
  node:
    id: ${node-id}
  replenish-threshold: ${key-replenish-threshold:200}

redis:
  hostName: ${redis-host-url}
  port: ${redis-port}
