server:
  port: 8093

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${github-client-id}
            clientSecret: ${github-client-secret}

key-generator:
  name: ${key-generation-strategy}
  node:
    id: ${node-id}
  replenish-threshold: ${key-replenish-threshold:200}

redis:
  hostName: ${redis-host-url}
  port: ${redis-port}
