apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tiny-url-redis-service
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
