apiVersion: v1
kind: Service
metadata:
  labels:
    app: tiny-url-redis-service
  name: tiny-url-redis-service
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: tiny-url-redis-service
