apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tiny-url-redis-service
  name: tiny-url-redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-url-redis-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tiny-url-redis-service
    spec:
      containers:
        - image: redis
          name: tiny-url-redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
