apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../scripts/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: key-generator
  name: key-generator
spec:
  ports:
    - name: service-port
      port: 8093
      protocol: TCP
      targetPort: 8093
  selector:
    io.kompose.service: key-generator
status:
  loadBalancer: {}
