version: "3"
volumes:
  redis-data:
  mongodb-data:
services:
  redis:
    container_name: tiny-url-redis
    image: localhost:5001/redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  mongo:
    image: localhost:5001/mongo
    container_name: tiny-url-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data
  key-generator:
    image: localhost:5001/key-generator
    container_name: tiny-url-key-generator
    ports:
      - "8093:8093"
    environment:
      node-id: 101
      replenish-threshold: 5
      redis-host-url: redis
      redis-port: 6379
    depends_on:
      - redis
  tiny-url-api:
    image: localhost:5001/tiny-url-api
    container_name: tiny-url-api
    ports:
      - "9093:9093"
    environment:
      mongodb-url: mongo
      mongodb-schema: tinyurldb
      mongodb-user: tinyuser
      mongodb-password: password
      KEY-GENERATOR-SERVER-URL: key-generator
      SHORT-URL-HOST: http://localhost:9093
    depends_on:
      - mongo
