server:
  shutdown: graceful
  port: 8095

spring:
  data:
    mongodb:
      uri: mongodb://${mongodb-user}:${mongodb-password}@${mongodb-url}/${mongodb-schema}
      authentication-database: admin
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: ${github-client-id}
#            clientSecret: ${github-client-secret}

mongock:
  migration-scan-package:
    - com.zemoso.systemdesignbootcamp.tinyurlapi.changelogs
  track-ignored: true
#  transaction-enabled: true

short-url-host: ${SHORT-URL-HOST}

urls:
  key-generator:
    base: ${KEY-GENERATOR-SERVER-URL}
    next: '${urls.key-generator.base}/api/v1/key'

