apiVersion: v1
kind: Service
metadata:
  labels:
    app: tiny-url-api
  name: tiny-url-api
spec:
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app: tiny-url-api
