apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tiny-url-api
  name: tiny-url-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-url-api
  strategy: {}
  template:
    metadata:
      labels:
        app: tiny-url-api
    spec:
      containers:
        - image: localhost:5000/tiny-url-api
          name: tiny-url-api
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
          resources: { }
          env:
            - name: SERVER-PORT
              value: ${TINY_URL_API_SERVICE_PORT}
            - name: KEY-GENERATOR-SERVER-URL
              value: "http://${KEY_GENERATOR_SERVICE_HOST}:${KEY_GENERATOR_SERVICE_PORT}"
            - name: SHORT-URL-HOST
              value: https://my-tiny-url
            - name: mongodb-password
              value: password
            - name: mongodb-schema
              value: tinyurldb
            - name: mongodb-url
              value: "${TINY_URL_MONGODB_SERVICE_HOST}:${TINY_URL_MONGODB_SERVICE_PORT}"
            - name: mongodb-user
              value: tinyuser
      restartPolicy: Always
