apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tiny-url-api
  name: tiny-url-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-url-api
  strategy: {}
  template:
    metadata:
      labels:
        app: tiny-url-api
    spec:
      containers:
        - image: localhost:5000/tiny-url-api
          name: tiny-url-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9093
          resources: { }
          env:
            - name: SERVER-PORT
              value: ${TINY_URL_API_SERVICE_PORT}
            - name: KEY-GENERATOR-SERVER-URL
              valueFrom:
                configMapKeyRef:
                  name: tiny-url-config
                  key: KEY_GENERATOR_SERVER_URL
            - name: SHORT-URL-HOST
              value: http://mytinyurl.com
            - name: mongodb-schema
              valueFrom:
                configMapKeyRef:
                  name: tiny-url-config
                  key: MONGODB_SCHEMA
            - name: mongodb-url
              valueFrom:
                configMapKeyRef:
                  name: tiny-url-config
                  key: MONGODB_URL
            - name: mongodb-user
              valueFrom:
                secretKeyRef:
                  name: tiny-url-secrets
                  key: MONGODB_USER
            - name: mongodb-password
              valueFrom:
                secretKeyRef:
                  name: tiny-url-secrets
                  key: MONGODB_PASSWORD
      restartPolicy: Always
